services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DARK_MODE=true #optional
    volumes:
      - ./Config:/config
    shm_size: "1gb"
    labels:
      - traefik.enable=true
      - traefik.http.routers.bambustudio.entryPoints=websecure
      - traefik.http.routers.bambustudio.rule=Host(`bambustudio.vanko.be`)
      - traefik.http.routers.bambustudio.tls=true
      - traefik.http.routers.bambustudio.tls.certResolver=cloudflare
      - traefik.http.services.bambustudio.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true
