services:
  geox:
    container_name: geox
    image : gregoryvanko/geox
  #  ports:
  #    - 9999:9999
    environment:
      - MONGOURL=mongodb://mongo:27017
    labels:
      - traefik.enable=true
      - traefik.http.routers.geox.entryPoints=websecure
      - traefik.http.routers.geox.rule=Host(`geox.vanko.be`)
      - traefik.http.routers.geox.tls=true
      - traefik.http.routers.geox.tls.certResolver=cloudflare
    networks:
      - frontend

networks:
  frontend:
    external: true
