services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "8081:8081" #default mqtt port for websockets
    volumes:
      - type : volume
        source: Nas-Docker
        target : /mosquitto/config
        volume :
          subpath: Mosquitto/Config
      - type : volume
        source: Nas-Docker
        target : /mosquitto/data
        volume :
          subpath: Mosquitto/Data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqtt-https.entrypoints=websecure"
      - "traefik.http.routers.mqtt-https.rule=Host(`mqtt.test.gregvanko.com`)"
      - "traefik.http.services.mqtt-https.loadbalancer.server.port=8081"
      - "traefik.http.routers.mqtt-https.tls=true"
      - "traefik.http.routers.mqtt-https.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend:
    external: true
volumes:
  Nas-Docker:
    external : true
