services:
  traefik:
    container_name: traefik
    image: traefik:3.4.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      #- "--entryPoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /DockerConfig/Traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /DockerConfig/Traefik/conf/:/etc/traefik/conf/
      - /DockerConfig/Traefik/certs/:/etc/traefik/certs/
    #environment:
      #- CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?error}
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend:
    external: true
