services:
  traefik:
    container_name: traefik
    image: traefik:3.4.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /DockerConfig/Traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /DockerConfig/Traefik/conf/:/etc/traefik/conf/
      - /DockerConfig/Traefik/certs/:/etc/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?error}
    networks:
      - frontend
    restart: unless-stopped
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx-1
    volumes:
      - /DockerConfig/Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /DockerConfig/Nginx/html:/usr/share/nginx/html
    labels:
      - "traefik.http.routers.nginx-demo-1-https.entrypoints=websecure"
      - "traefik.http.routers.nginx-demo-1-https.rule=Host(`demo1.test.gregvanko.com`)"
      - "traefik.http.routers.nginx-demo-1-https.tls=true"
      - "traefik.http.routers.nginx-demo-1-https.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stoppedv  
networks:
  frontend:
    external: true
