services:
  traefik:
    container_name: traefik
    image: traefik:3.4.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./Config/conf/:/etc/traefik/conf/
      - ./Config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?error}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.test.gregvanko.com`)"
      - "traefik.http.services.traefik-https.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend:
    external: true
