services:
  traefik:
    container_name: traefik
    image: traefik:3.4.3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - type : volume
        source: Nas-Docker
        target : /etc/traefik/
        volume :
          subpath: Test/Traefik/
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:?error}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.test.gregvanko.com`)"
      - "traefik.http.services.traefik-https.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped  
networks:
  frontend:
    external: true
volumes:
  Nas-Docker:
    external : true
